use_frameworks!

platform :ios, '8.0'

target 'BYAllModule_Example' do
  pod 'BYAllModule', :path => '../'

  target 'BYAllModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
